Check AtomicReference's value by Predicate and Consumer
assertj/assertj-core pull request #1950
Opened 2020-07-27 15:18 UTC by valery1707

#### Check List:
* There are no opened issues
* Unit tests: YES
* Javadoc with a code example (on API only): YES

2020-07-27 15:18 UTC, valery1707 commented
Do I need to add `@since` tag to JavaDoc? With which value?

2020-08-07 05:45 UTC, valery1707 commented
@joel-costigliola ping

2020-08-26 11:04 UTC, valery1707 commented
@joel-costigliola ping

2020-08-27 23:54 UTC, joel-costigliola commented
@valery1707 thanks we'll look into it for 3.18.0

2020-10-01 05:25 UTC, joel-costigliola requested changes
PR commented, thanks @valery1707

2020-10-01 05:25 UTC, joel-costigliola commented on src/main/java/org/assertj/core/api/AtomicReferenceAssert.java
> +   * // assertion will pass
join lines and leave one space after `<pre><code class='java'>`:
```
<pre><code class='java'> // assertion will pass
```

2020-10-01 05:25 UTC, joel-costigliola commented on src/main/java/org/assertj/core/api/AtomicReferenceAssert.java
> +   * </code></pre>
join lines

2020-10-01 05:25 UTC, joel-costigliola commented on src/main/java/org/assertj/core/api/AtomicReferenceAssert.java
> +  public AtomicReferenceAssert<V> hasValueSatisfies(Consumer<? super V> requirements) {
rename to `hasValueSatisfying`

2020-10-01 05:25 UTC, joel-costigliola commented on src/main/java/org/assertj/core/api/AtomicReferenceAssert.java
> +    return hasValueMatching(predicate, new PredicateDescription(description));
nice!

2020-10-01 05:25 UTC, joel-costigliola commented on src/test/java/org/assertj/core/api/atomic/reference/AtomicReferenceAssert_hasValueMatching_Test.java
> +  void should_pass_when_actual_has_value_which_is_match() {
rename to `should_pass_when_actual_has_value_matching_predicate`

2020-10-01 05:25 UTC, joel-costigliola commented on src/test/java/org/assertj/core/api/atomic/reference/AtomicReferenceAssert_hasValueMatching_Test.java
> +  void should_fail_when_actual_has_value_which_does_not_match_without_description() {
rename: `should_pass_when_actual_has_value_not_matching_predicate_without_description`

2020-10-01 05:25 UTC, joel-costigliola commented on src/test/java/org/assertj/core/api/atomic/reference/AtomicReferenceAssert_hasValueMatching_Test.java
> +  void should_fail_when_actual_has_value_which_does_not_match_with_description() {
rename: `should_pass_when_actual_has_value_not_matching_predicate_with_description`

2020-10-01 05:25 UTC, joel-costigliola commented on src/test/java/org/assertj/core/api/atomic/reference/AtomicReferenceAssert_hasValueMatching_Test.java
> +      .withMessageContaining("a better error message");
use [`withMessageContainingAll`](https://www.javadoc.io/static/org.assertj/assertj-core/3.17.2/org/assertj/core/api/ThrowableAssertAlternative.html#withMessageContainingAll(java.lang.CharSequence...)) assertion

2020-10-01 05:25 UTC, joel-costigliola commented on src/test/java/org/assertj/core/api/atomic/reference/AtomicReferenceAssert_hasValueSatisfies_Test.java
> +      .withMessageContaining("Consumer");
put the full message

2020-10-11 01:29 UTC, closed without merging