Add doesNotHaveToString assertion
assertj/assertj-core pull request #2052
Opened 2020-11-26 02:12 UTC by lykims

#### Check List:
* Fixes #2028 
* Unit tests : YES
* Javadoc with a code example (on API only) : YES

Minor fixes for `hasToString` doc description and `ShouldHaveToString` error as well.

2020-11-29 09:45 UTC, joel-costigliola requested changes
@lykims thanks, good PR, just a few improvements to do and we are good.

2020-11-29 09:45 UTC, joel-costigliola commented on src/main/java/org/assertj/core/api/Assert.java
> +   * </code></pre>
join the two lines

2020-11-29 09:45 UTC, joel-costigliola commented on src/main/java/org/assertj/core/error/ShouldNotHaveToString.java
> +    super("%nExpecting actual's toString() not to be equal to:%n  <%s>%nbut was:%n  <%s>", other, actual.toString());
let's simplify this to:
```
"%nExpecting actual's toString() not to be equal to:%n  <%s>"
```
the reason is `but was:%n  <%s>` section is actually repeating actual's `toString` value

2020-11-29 09:45 UTC, joel-costigliola commented on src/test/java/org/assertj/core/internal/objects/Objects_assertDoesNotHaveToString_Test.java
> +    ThrowingCallable code = () -> objects.assertDoesNotHaveToString(someInfo(), actualObject, "bar");
use `expectAssertionError` from `org.assertj.core.util.AssertionsUtil` which returns an `AssertionError`

2020-11-29 09:45 UTC, joel-costigliola commented on src/test/java/org/assertj/core/internal/objects/Objects_assertDoesNotHaveToString_Test.java
> +    assertThat(error).hasMessageContainingAll("Person[name='foo']");
remove this line, it is already covered by `verify(failures)` (we don't want to test the error message but only that we call the proper error message factory)

2020-11-29 09:45 UTC, joel-costigliola commented on src/test/java/org/assertj/core/internal/objects/Objects_assertDoesNotHaveToString_Test.java
> +    AssertionError error = expectAssertionError(() -> objects.assertDoesNotHaveToString(info, actual, "Person[name='foo']"));
remove `AssertionError error` local variable (see next comment why)

2020-11-29 19:17 UTC, lykims commented
@joel-costigliola I addressed your comments. I also applied changes suggested for `Objects_assertDoesNotHaveToString_Test` to `Objects_assertHasToString_Test`. Let me know if I miss anything!

2020-11-30 09:56 UTC, joel-costigliola approved these changes

2020-11-30 09:57 UTC, merged

2020-11-30 09:57 UTC, joel-costigliola commented
Integrated thanks for the good work @lykims!