Issue 1466
assertj/assertj-core pull request #2150
Opened 2021-03-16 21:54 UTC by mbaechler

#### Check List:
* Implements #1466 
* Unit tests : OF COURSE
* Javadoc with a code example (on API only) : YES

2021-04-28 16:06 UTC, mbaechler commented
Anybody willing to review and merge this PR?

2021-04-28 21:56 UTC, joel-costigliola commented
Has fallen under our radar, we'll try for the next release

2021-04-28 23:50 UTC, joel-costigliola requested changes

2021-04-28 23:50 UTC, joel-costigliola commented on src/test/java/org/assertj/core/api/iterable/IterableAssert_elements_Test.java
> +    AssertionError assertionError = expectAssertionError(() -> assertThat(iterable).elements(5));
minor: add `// WHEN`

2021-04-30 07:37 UTC, mbaechler commented
I rebased on `main` and added a fixup commit with fixes from your review.

2021-05-03 04:12 UTC, joel-costigliola commented
Integrated thanks @mbaechler!
I made the code compatible with soft assertions which lead me to revert the changes you made due to one of my comments on using IllegalArgumentException for checking the indices validity (sorry I did see that).

2021-05-03 04:12 UTC, closed without merging