I1006
assertj/assertj-core pull request #2209
Opened 2021-05-13 18:01 UTC by RGalways17

Show the stack trace for the `Throwable` when `hasCauseInstanceOf` and `hasCauseExactlyInstanceOf` fails. I also noticed that there was only test for no cause, so I decided for myself to write a test on wrong cause. Please let me know if there is any problem.

#### Check List:
* Fixes #1355
* Unit tests : YES
* Javadoc with a code example (on API only) : NA

2021-05-14 10:55 UTC, joel-costigliola requested changes
Thanks @RGalways17, just some minor comments!

2021-05-14 10:55 UTC, joel-costigliola commented on src/test/java/org/assertj/core/error/ShouldHaveCauseExactlyInstance_create_Test.java
> +  }
`isEqualTo` for String as an overload version that supports the `String.format` syntax, you can then remove the call to `format` here.

Also can you add a cause message containing a `%` to make sure it does not break the code?

see https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractStringAssert.html

this comment applies to the other tests too ;-)

2021-05-18 07:05 UTC, RGalways17 commented
@joel-costigliola I've finished the syntax correction. Not quite sure about what you mean by 'cause message containing a %'? Do you mean `then(message).isEqualTo("......" +
      "Cause message :%n" +
      "  %s%n" +
      "......" +
      "%n" + escapePercent(getStackTrace(actual)),...,..., causeMessage);`
The cause of the actual throwable should be already displayed in the message like this:
`Throwable that failed the check:

java.lang.RuntimeException: java.lang.IllegalAccessError
.....
Caused by: java.lang.IllegalAccessError
.....
`

2021-05-18 07:08 UTC, RGalways17 commented
@joel-costigliola I've finished the syntax correction. Not quite sure about what you mean by 'cause message containing a %'? Do you mean `then(message).isEqualTo("......" +
      "Cause message :%n" +
      "  %s%n" +
      "......" +
      "%n" + escapePercent(getStackTrace(actual)),...,..., causeMessage);` ?
The cause of the actual throwable should be already displayed in the message like this:
`Throwable that failed the check:

java.lang.RuntimeException: java.lang.IllegalAccessError
.....
Caused by: java.lang.IllegalAccessError
.....
`

2021-05-18 07:09 UTC, RGalways17 commented
@joel-costigliola I've finished the syntax correction. Not quite sure about what you mean by 'cause message containing a %'? Do you mean then(message).isEqualTo("......" + "Cause message :%n" + " %s%n" + "......" + "%n" + escapePercent(getStackTrace(actual)),...,..., causeMessage); ?
The cause of the actual throwable should be already displayed in the message like this:
`Throwable that failed the check:

java.lang.RuntimeException: java.lang.IllegalAccessError
.....
Caused by: java.lang.IllegalAccessError
.....`

2021-05-18 07:10 UTC, RGalways17 commented
@joel-costigliola I've finished the syntax correction. Not quite sure about what you mean by 'cause message containing a %'? Do you mean 
`then(message).isEqualTo("......" + "Cause message :%n" + " %s%n" + "......" + "%n" + escapePercent(getStackTrace(actual)),...,..., causeMessage);` ?
The cause of the actual throwable should be already displayed in the message like this:
`Throwable that failed the check:

java.lang.RuntimeException: java.lang.IllegalAccessError
.....
Caused by: java.lang.IllegalAccessError
.....`

2021-05-18 10:28 UTC, joel-costigliola commented
I was saying to create the cause exception with a message having a `%`, ex: 
```java
Throwable cause = new IllegalAccessError("boom % %n");
```
I want to make sure that `these %` are not interpreted as `String.format` arguments.

2021-05-18 14:48 UTC, RGalways17 commented
@joel-costigliola I've finished modifying the code. Please check :-).

2021-07-17 11:29 UTC, closed without merging

2021-07-17 11:33 UTC, joel-costigliola commented
Integrated thanks @RGalways17!