Issue 2060 StringAssert: add variants with "Ignoring"
assertj/assertj-core pull request #2416
Opened 2021-11-19 00:44 UTC by spring1627

#### Check List:
* Fixes #2060 (partially)
* Unit tests : YES
* Javadoc with a code example (on API only) : YES
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md)

Following the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md) will make it easier for us to review and accept your PR.

2021-11-20 22:55 UTC, joel-costigliola commented
Thanks, we will review your PR shortly!

2021-11-20 23:09 UTC, joel-costigliola requested changes
Thanks @spring1627 , first round of code review done.

2021-11-20 23:09 UTC, joel-costigliola commented on src/main/java/org/assertj/core/internal/Strings.java
> +    final Stream<CharSequence> notFoundStream2 = mapContainsIgnoringNewLines(notFoundStream);
inlining both `notFoundStream` and `mapContainsIgnoringNewLines` would make the code clearer I think, here it's confusing to have `notFoundStream` and `notFoundStream2`.
might look like:
```java
Set<CharSequence> notFound = stream(values).map(Strings::removeNewLines)
                                           .filter(value -> !stringContains(actualNoNewLines, value))
                                           .collect(toCollection(LinkedHashSet::new));
```

2021-11-20 23:09 UTC, joel-costigliola commented on src/main/java/org/assertj/core/internal/Strings.java
> +  private boolean isEmptyContainsIgnoringNewLines(final Set<CharSequence> notFound) {
inline this as the inline code is as clear as this method name

2021-11-20 23:09 UTC, joel-costigliola commented on src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_containsIgnoringNewLines_CharSequence_Test.java
> +    } catch (CloneNotSupportedException e) {
no need to deal with CloneNotSupportedException

2021-11-20 23:09 UTC, joel-costigliola commented on src/test/java/org/assertj/core/internal/strings/Strings_assertContainsIgnoringNewLines_Test.java
> +  @ParameterizedTest
nice!

2021-11-24 03:29 UTC, joel-costigliola commented on src/main/java/org/assertj/core/internal/Maps.java
> +    System.out.println(actual.toString());
remove all System.out, better debugging with an IDE ;-)

2021-11-24 03:29 UTC, joel-costigliola commented on src/test/java/org/example/custom/map_test.java
> +  // ============================= MY TEST HERE ===================================================
remove

2021-11-24 03:30 UTC, joel-costigliola commented on src/test/java/org/example/custom/map_test.java
> +public class map_test extends MapsBaseTest {
use proper naming convention (look at the other test classes if you are not sure)

2021-11-24 03:31 UTC, joel-costigliola commented on src/test/java/org/example/custom/map_test.java
> +public class map_test extends MapsBaseTest {
and please follow the contributing guide https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md thanks!

2021-11-24 03:32 UTC, joel-costigliola requested changes
please address the first comments we have before we can review this PR fully, thanks

2021-11-25 09:01 UTC, joel-costigliola commented on src/test/java/org/assertj/core/internal/files/Files_assertHasDigest_AlgorithmString_Test.java
> +@DisplayName("Files.assertHasDigest_AlgorithmString:")
no need to add any `DisplayName` as they are automatically computed

2021-11-25 09:06 UTC, joel-costigliola commented on src/test/java/org/assertj/core/internal/files/File_assertHasSize_Test.java
> +    assertThat(error).isInstanceOf(AssertionError.class);
`expectAssertionError` already makes sure the error is an `AssertionError`, please revert all the changes in this file.
The only thing to do is remove @DisplayName("Files.assertHasSizeInBytes:") as it is computed automatically

2021-11-25 09:07 UTC, joel-costigliola commented
@ahmadsadeed could you address the comments in this PR before adding more code? thanks!

2021-11-25 20:19 UTC, scordio commented
Something is strange with this PR, files unrelated to the original issue are having changes.

@spring1627 could you please have a look at the commits of this branch and push a clean history?

2021-11-25 21:12 UTC, ahmadsadeed commented
> Something is strange with this PR, files unrelated to the original issue are having changes.
> 
> @spring1627 could you please have a look at the commits of this branch and push a clean history?

Is it the files starting with Files_ ? I was working on issue #2337 and pushed my commit to our group [repo](https://github.com/sandeep-yerramsetty/assertj-core)  . My commit was not supposed to be included in this PR because I made a separate [PR](https://github.com/assertj/assertj-core/pull/2422) from my Github account. My commit was merged with the main branch where @spring1627 pushed their code for issue 2060. I suggest @spring1627 make a new commit with changes only for issue 2060 from their github account. I will push my changes to issue 2337 on my forked [repo](https://github.com/assertj/assertj-core/pull/2422). This way each PR will be specific to one issue.

2022-01-23 04:06 UTC, joel-costigliola commented
closing this PR as it was mixed up with another one

2022-01-23 04:06 UTC, closed without merging