Increase abstractassert test coverage
assertj/assertj-core pull request #2527
Opened 2022-03-17 20:23 UTC by sarajuhosova

#### Check List:
* Fixes: NA
* Unit tests : YES
* Javadoc with a code example (on API only) : NA
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md): NA

Following the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md) will make it easier for us to review and accept your PR.

2022-03-19 04:17 UTC, joel-costigliola requested changes
thanks a lot @sarajuhosova for this great PR.
I have a few comments that are mainly stylistic and for simplifying the code a bit more.

2022-03-19 04:17 UTC, joel-costigliola commented on src/test/java/org/assertj/core/api/inputstream/InputStreamAssert_asString_with_charset_Test.java
> +    }).isInstanceOf(InputStreamsException.class);
Minor: restructure the test from the ASSERT THROWS comment as:
```java
   // WHEN/THEN
   thenThrownBy(() -> assertThat(inputStream).asString(TURKISH_CHARSET).isEqualTo(real)).isInstanceOf(InputStreamsException.class);
``` 
an alternative would be:
```java
   // WHEN
   ThrowingCallable assertionCall = () -> assertThat(inputStream).asString(TURKISH_CHARSET).isEqualTo(real);
   // WHEN/THEN
   thenThrownBy(assertionCall).isInstanceOf(InputStreamsException.class);
```
pick the one that is most readable to you ;-)

2022-03-19 04:17 UTC, joel-costigliola commented on src/test/java/org/assertj/core/api/optional/OptionalAssert_contains_usingDefaultComparator_Test.java
> +  void should_succeed_if_default_equal_content() {
add // GIVEN

2022-03-19 04:17 UTC, joel-costigliola commented on src/test/java/org/assertj/core/api/optional/OptionalAssert_contains_usingDefaultComparator_Test.java
> +    // go back to default strategy
add // WHEN/THEN

2022-03-19 04:17 UTC, joel-costigliola commented on src/test/java/org/assertj/core/api/optional/OptionalAssert_contains_usingDefaultComparator_Test.java
> +      );
use the simpler `expectAssertionError` from `AssertionsUtil` over `assertThatExceptionOfType(AssertionError.class)`

2022-03-19 09:25 UTC, sarajuhosova commented
Thanks, @joel-costigliola, for the feedback, I'll fix the style issues asap. I was also planning to add tests for the more complex classes that I've left out for now, should I add it to this PR or make a new on to make reviewing a bit easier?

2022-03-19 09:42 UTC, joel-costigliola commented
thanks for the quick reply, I would prefer another PR so that we can finish this one and it's easier to review shorter PRs.

2022-03-19 10:12 UTC, sarajuhosova commented
I've fixed the commented things, hopefully this is what you meant!

2022-03-20 05:24 UTC, joel-costigliola commented
Integrated thanks @sarajuhosova!
I noticed when integrating some unused imports or `*` imports and I tool the liberty to reformat other tests not initially in the PR and squashed all the commits (keeping you as the commit author obviously)

2022-03-20 05:24 UTC, closed without merging